<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ion</string>
	</array>
	<key>keyEquivalent</key>
	<string>@i</string>
	<key>name</key>
	<string>Ion</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return|struct|switch|default|continue|break|case|typedef|else|enum)\b</string>
			<key>name</key>
			<string>keyword.control.ion</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ion</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ion</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(func)[\n\t ]*(.+)\(</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(true|false|NULL)</string>
			<key>name</key>
			<string>constant.language.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9]+(\.)[0-9]+)d*</string>
			<key>name</key>
			<string>constant.numeric.float.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0b([0-1]+)(l|u|ll|ull)*\b</string>
			<key>name</key>
			<string>constant.numeric.decimal.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0x([0-9A-Fa-f]+)(l|u|ll|ull)*\b</string>
			<key>name</key>
			<string>constant.numeric.hex.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+)(l|u|ll|ull)*\b</string>
			<key>name</key>
			<string>constant.numeric.decimal.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sizeof)\b</string>
			<key>name</key>
			<string>keyword.operator.sizeof.c</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#|@)foreign</string>
			<key>name</key>
			<string>meta.preprocessor.macro.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/\*.*\*/</string>
			<key>name</key>
			<string>comment.line.block.ion</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.line.block.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(const|var)\b</string>
			<key>name</key>
			<string>storage.modifier.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(int|float|void|uint64|uint32|uint16|uint8|ullong|char)\b</string>
			<key>name</key>
			<string>storage.type.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|&lt;=|&gt;=|&gt;|&lt;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.logic.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(~|\^|&amp;&amp;|&amp;)</string>
			<key>name</key>
			<string>keyword.operator.binary.ion</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.ion</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[([^\n\t ]*)\]</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:=|=)|(\*)+</string>
			<key>name</key>
			<string>keyword.operator.assignment.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*\n</string>
			<key>name</key>
			<string>comment.line.double-slash.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+\+|\-\-|\+|\-|\-\=|/)</string>
			<key>name</key>
			<string>keyword.operator.math.ion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:</string>
			<key>name</key>
			<string>keyword.operator.assignment.ion</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.ion</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.ion</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.ion</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((\:)([^*]*(\*)*)\)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.triple.ion</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(r|n|t|v|a|b)</string>
					<key>name</key>
					<string>constant.character.escape.ion</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%(d|s|c|p|x|llu|lu|f)</string>
					<key>name</key>
					<string>constant.character.other.ion</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ion</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(r|n|t|v|a|b)</string>
					<key>name</key>
					<string>constant.character.escape.ion</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%(d|s|c|p|x|llu|lu|f)</string>
					<key>name</key>
					<string>constant.character.other.ion</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.ion</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(r|n|t|v|a|b)</string>
					<key>name</key>
					<string>constant.character.escape.ion</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%(d|s|c|p|x|llu|lu|f)</string>
					<key>name</key>
					<string>constant.character.other.ion</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ion</string>
	<key>uuid</key>
	<string>BBDED9C2-7276-44C4-ACA8-B7CD1F4A609E</string>
</dict>
</plist>
